freebsd_instance:
  image: freebsd-12-1-release-amd64
  
env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[6b1650a5965578230a926b9aa73b08644ea65e436ee302b1e7b793a55249d8fcbc2c16f7e0e61317233f2080ec2c5a72]
ccache_cache:
  folder: ${CCACHE_DIR}
pkg_cache:
  folder: /var/cache/pkg/
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  stateful: false
  setup_script:
    - pkg install -y git-lite curl wget zip cmake pkgconf qt5-core qt5-widgets
  ccache_setup_script:
    - env IGNORE_OSVERSION=yes pkg install -y ccache-static
    - ccache --max-size=${CCACHE_SIZE}
    - echo "WITH_CCACHE_BUILD=yes" >> /etc/make.conf
  test_script:
    - git submodule update --init --recursive
    - mkdir build ; cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make DESTDIR=. -j$(sysctl -n hw.ncpu) install
    - find Filer.app/
    - ( cd ./ ; zip --symlinks -r ../Filer_FreeBSD.zip Filer.app/ )
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; ./ghr -replace -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
