name: Build for Alpine
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container: alpine:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache \
            git \
            curl \
            wget \
            zip \
            cmake \
            pkgconf \
            qt5-qtbase-dev \
            qt5-qttools-dev

      - name: Build and package
        run: |
          git submodule update --init --recursive
          mkdir build ; cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          make DESTDIR=. install
          find Filer.app/
          zip --symlinks -r ./Filer_Alpine.zip Filer.app/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: filer-artifact
          path: build/Filer_Alpine.zip
