name: Build for Ubuntu
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl wget zip cmake pkgconf libqt5widgets5 qttools5-dev

      - name: Build and package
        run: |
          git submodule update --init --recursive
          mkdir build ; cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          make DESTDIR=. install
          find Filer.app/
          zip --symlinks -r ./Filer_Ubuntu.zip Filer.app/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: filer-artifact
          path: build/Filer_Ubuntu.zip

      - name: Create GitHub Release using Continuous Release Manager
        run: |
          curl -L -o continuous-release-manager-amd64 https://github.com/probonopd/continuous-release-manager/releases/download/continuous/continuous-release-manager-amd64
          chmod +x continuous-release-manager-amd64
          ./continuous-release-manager-amd64

      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Content-Type: $(file -b --mime-type build/Filer_Ubuntu.zip)" \
               --data-binary "@build/Filer_Ubuntu.zip" \
               "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${GITHUB_RUN_ID}/assets?name=Filer_Ubuntu.zip"
